name = "Synixe Equipment"
author = "Synixe Contractors"
prefix = "synixe_equipment"
mainprefix = "s"

[hemtt.launch.default]
workshop = [
    "450814997", # CBA
    "463939057", # ACE3
    "1779063631", # Zeus Enhanced
]
